In [2]:
import numpy as np

### Creating Arrays

In [10]:
arr0 = np.array(1)
print(arr0)
print("dimension:", arr0.ndim)

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print("dimension:", arr1.ndim)

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
print("dimension:", arr2.ndim)

1
dimension: 0
[1 2 3 4 5]
dimension: 1
[[1 2 3]
 [4 5 6]]
dimension: 2


### Array indexing

In [5]:
arr = np.array([1, 2, 3, 4])
print(arr[1] + arr[3])

6


In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print('2nd element on the first row is: ',arr[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on the first row is:  2


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
9


### Array Copy vs View

In [15]:
# copy is a copy, will not affect the orignal array 
# view is a view of the original array, will affect the orignal array

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 10

print(arr)
print(x)
print(x.base) # copy return none

y = arr.view()
print(arr)
print(y)
print(y.base) # view returns the original array

[10  2  3  4  5]
[1 2 3 4 5]
None
[10  2  3  4  5]
[10  2  3  4  5]
[10  2  3  4  5]
